add giga-embedding-instruct model
embeddings-benchmark/results pull request #77
Opened 2024-12-20 01:14 UTC by ekolodin

## Checklist

- [ ] Run tests locally to make sure nothing is broken using `make test`. 
- [ ] Run the results files checker `make pre-push`.

### Adding a model checklist

Ref # 

- I have added model implementation to `mteb/models/` [directory](https://github.com/embeddings-benchmark/mteb/tree/main/mteb/models). Instruction to add a model can be found [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/reproducible_workflow.md)

2024-12-20 07:16 UTC, Samoed commented
Could you run `MiraclReranking` with the current MTEB version since its score format has changed? Also, could you add the implementation to the MTEB repository?

2025-02-05 07:54 UTC, KennethEnevoldsen requested changes
~~Sorry for the delay on this

The result format is good. 

Just to make you aware you will have to submit a model meta to the mteb repo for it to appear on the leaderboard.

The model meta file is also unfilled~~

2025-02-05 08:43 UTC, Samoed commented
@KennethEnevoldsen https://github.com/embeddings-benchmark/mteb/pull/1741

2025-02-05 16:33 UTC, KennethEnevoldsen commented
Ah yes I see - I could have seen that from the reference

2025-03-19 20:57 UTC, KennethEnevoldsen commented
Re-reviewed this PR. Seems like the revision is missing. I don't think we can merge it without it. However @Samoed's implementation has been merged so it should be easy to rerun. 

Will close this PR  for now, but do open a new one

2025-03-19 20:57 UTC, closed without merging